server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/register
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
